version: "3.9" # Versi칩n del esquema de Docker Compose

services:
  docker:
    container_name: docker # Nombre del contenedor Docker
    image: docker:dind # Imagen de Docker para Docker-in-Docker (dind)
    privileged: true # Ejecutar en modo privilegiado para permitir el uso de Docker dentro del contenedor
    restart: always # Reiniciar el contenedor autom치ticamente en caso de fallo
    volumes:
      - jenkins-data:/var/jenkins_home # Volumen para almacenar los datos de Jenkins
      - jenkins-docker-certs:/certs/client # Volumen para almacenar los certificados TLS de Docker
    environment:
      DOCKER_TLS_CERTDIR: /certs # Directorio de certificados TLS para Docker

  jenkins:
    container_name: roxs-jenkins # Nombre del contenedor Jenkins
    image: roxsross12/jenkins:1.0.0 # Imagen personalizada de Jenkins
    restart: always # Reiniciar el contenedor autom치ticamente en caso de fallo
    depends_on:
      - docker # Asegurar que el servicio Docker se inicie antes de Jenkins
    volumes:
      - jenkins-data:/var/jenkins_home # Volumen compartido con Docker para almacenar los datos de Jenkins
      - jenkins-docker-certs:/certs/client:ro # Volumen para certificados TLS de Docker, montado en modo de solo lectura (ro)
    environment:
      DOCKER_HOST: tcp://docker:2376 # Configuraci칩n del host Docker para Jenkins
      DOCKER_TLS_VERIFY: 1 # Verificar los certificados TLS
      DOCKER_CERT_PATH: /certs/client # Ruta de los certificados TLS
    ports:
      - "8080:8080" # Mapeo del puerto para la interfaz web de Jenkins
      - "50000:50000" # Mapeo del puerto para los agentes de Jenkins

volumes:
  jenkins-data: # Volumen para almacenar los datos de Jenkins
  jenkins-docker-certs: # Volumen para almacenar los certificados TLS de Docker
