name: Build

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push a la rama 'main'
  pull_request:
    branches:
      - main  # Se ejecuta cuando se crea un pull request hacia la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usa la última versión de Ubuntu como entorno de ejecución
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clona el repositorio

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Configura Docker Buildx para construcciones multiplataforma

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache  # Define la ruta para almacenar la caché de capas de Docker
        key: ${{ runner.os }}-buildx-${{ github.sha }}  # Define una clave única para la caché basada en el sistema operativo y el SHA del commit
        restore-keys: |
          ${{ runner.os }}-buildx-  # Clave de restauración en caso de que la clave principal no se encuentre

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Directorio de contexto para la construcción de Docker
        push: false  # No se empuja la imagen al registro
        tags: user/repo:latest  # Etiqueta de la imagen Docker
